export const REDUCER_TYPE = {
  NETWORK_STATUS: 'network_status',
  RESET_STORE: 'RESET_STORE',
  IS_OPEN_FIRST_TIME: 'is_open_first_time',
  SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
  TOGGLE_DARK_THEME: 'TOGGLE_DARK_THEME',
  SET_THEME_FIRST_TIME: 'SET_THEME_FIRST_TIME',
  CHANGE_THEME: 'CHANGE_THEME',
  SET_GRADIENT_COLOR: 'SET_GRADIENT_COLOR',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
};
