export const REDUCER_TYPE = {
  NETWORK_STATUS: 'network_status',
  RESET_STORE: 'RESET_STORE',
  IS_OPEN_FIRST_TIME: 'is_open_first_time',
  SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
  TOGGLE_DARK_THEME: 'TOGGLE_DARK_THEME',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  IS_DRAWER_LEFTSIDE_COLLAPSED: 'IS_DRAWER_LEFTSIDE_COLLAPSED',
};
