export const REDUCER_TYPE = {
  NETWORK_STATUS: 'network_status',
  RESET_STORE: 'RESET_STORE',
  IS_OPEN_FIRST_TIME: 'is_open_first_time',
  SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
  SET_DARK_THEME: 'SET_DARK_THEME',
};
