/* eslint-disable camelcase */
export const images = {
  logo: require('./logo/logo.png'),
  background_logo: require('./background_logo/back_logo.png'),
  tribevest: require('./tribevest/tribevest.png'),
  tribes_active: require('./tribes_active/tribes_active.png'),
  tribes_inactive: require('./tribes_inactive/tribes_inactive.png'),
  messages_active: require('./messages_active/messages_active.png'),
  messages_inactive: require('./messages_inactive/messages_inactive.png'),
  alerts_active: require('./alerts_active/alerts_active.png'),
  alerts_inactive: require('./alerts_inactive/alert_inactive.png'),
  more_square: require('./more_square/more_square.png'),
  dashboard: require('./dashboard/dashboard.png'),
  wallet: require('./wallet/wallet.png'),
  dollar_circle: require('./dollar_circle/dollar_circle.png'),
  like: require('./like/like.png'),
  members: require('./members/members.png'),
  document: require('./document/document.png'),
  settings: require('./settings/settings.png'),
  document_white: require('./document_white/document_white.png'),
  chat: require('./chat/chat.png'),
  splash: require('./splash/Splash.png'),
  splashscreen_bg: require('./splashscreen_bg/splashscreen_bg.png'),
  onboarding_welcome: require('./onboarding_welcome/onboarding_welcome.png'),
  onboarding_invite_friends: require('./onboarding_invite_friends/onboarding_invite_friends.png'),
  onboarding_pool_capital: require('./onboarding_pool_capital/onboarding_pool_capital.png'),
  onboarding_file_llc: require('./onboarding_file_llc/onboarding_file_llc.png'),
  onboarding_create_plan: require('./onboarding_create_plan/onboarding_create_plan.png'),
  arrow_drop_down_circle: require('./arrow_drop_down_circle/arrow_drop_down_circle.png'),
};
